-- Basit güncelleme sorgusu
SET QUOTED_IDENTIFIER ON;

UPDATE [BigIntSoftware].[Customers] 
SET 
    [Email] = 'test' + CAST(Id AS NVARCHAR(10)) + '@test.com',
    [Phone] = '0212' + RIGHT('0000000' + CAST(Id AS NVARCHAR(10)), 7),
    [MobilePhone] = '0555' + RIGHT('0000000' + CAST(Id AS NVARCHAR(10)), 7),
    [Website] = 'www.test' + CAST(Id AS NVARCHAR(10)) + '.com',
    [Address] = 'Test Adres ' + CAST(Id AS NVARCHAR(10)),
    [City] = CASE WHEN Id % 5 = 0 THEN 'İstanbul' WHEN Id % 5 = 1 THEN 'Ankara' WHEN Id % 5 = 2 THEN 'İzmir' WHEN Id % 5 = 3 THEN 'Bursa' ELSE 'Antalya' END,
    [State] = CASE WHEN Id % 5 = 0 THEN 'İstanbul' WHEN Id % 5 = 1 THEN 'Ankara' WHEN Id % 5 = 2 THEN 'İzmir' WHEN Id % 5 = 3 THEN 'Bursa' ELSE 'Antalya' END,
    [PostalCode] = '34000',
    [Country] = 'Türkiye',
    [TaxNumber] = RIGHT('0000000000' + CAST(Id AS NVARCHAR(10)), 10),
    [VatNumber] = 'TR' + RIGHT('000000000000000000' + CAST(Id AS NVARCHAR(18)), 18),
    [TcNumber] = RIGHT('00000000000' + CAST(Id AS NVARCHAR(11)), 11),
    [MersisNumber] = RIGHT('00000000000000000000000000000000000000000000000000' + CAST(Id AS NVARCHAR(50)), 50),
    [Iban] = 'TR' + RIGHT('000000000000000000' + CAST(Id AS NVARCHAR(18)), 18),
    [BankName] = CASE WHEN Id % 3 = 0 THEN 'Ziraat Bankası' WHEN Id % 3 = 1 THEN 'İş Bankası' ELSE 'Garanti Bankası' END,
    [BankBranch] = 'Şube ' + CAST(Id AS NVARCHAR(10)),
    [BankAccountNumber] = RIGHT('000000000000000000000000000000' + CAST(Id AS NVARCHAR(30)), 30),
    [SwiftCode] = 'TR' + RIGHT('000000000000000000' + CAST(Id AS NVARCHAR(18)), 18),
    [CreditLimit] = CAST((Id * 1000) AS DECIMAL(18,2)),
    [DiscountRate] = CAST((Id % 20) AS DECIMAL(5,2)),
    [PaymentTermDays] = CASE WHEN Id % 3 = 0 THEN 30 WHEN Id % 3 = 1 THEN 15 ELSE 45 END,
    [Currency] = 'TRY',
    [TotalSales] = CAST((Id * 5000) AS DECIMAL(18,2)),
    [LastOrderDate] = DATEADD(DAY, -(Id % 365), GETDATE()),
    [EInvoiceAlias] = 'E-Fatura Alias ' + CAST(Id AS NVARCHAR(10)),
    [EInvoiceTitle] = 'E-Fatura Başlık ' + CAST(Id AS NVARCHAR(10)),
    [UpdatedDate] = GETDATE(),
    [UpdatedBy] = 'System',
    [Notes] = 'Test notları ' + CAST(Id AS NVARCHAR(10)),
    [InternalNotes] = 'İç notlar ' + CAST(Id AS NVARCHAR(10)),
    [CustomerGroup] = CASE WHEN Id % 4 = 0 THEN 'VIP' WHEN Id % 4 = 1 THEN 'Premium' WHEN Id % 4 = 2 THEN 'Standard' ELSE 'Basic' END,
    [CustomerSegment] = CASE WHEN Id % 3 = 0 THEN 'Kurumsal' WHEN Id % 3 = 1 THEN 'Bireysel' ELSE 'Karma' END,
    [Source] = CASE WHEN Id % 2 = 0 THEN 'Web' ELSE 'Telefon' END,
    [LinkedIn] = 'linkedin.com/in/test' + CAST(Id AS NVARCHAR(10)),
    [Twitter] = '@test' + CAST(Id AS NVARCHAR(10)),
    [Facebook] = 'facebook.com/test' + CAST(Id AS NVARCHAR(10)),
    [Instagram] = '@test' + CAST(Id AS NVARCHAR(10)),
    [DeliveryAddress] = 'Teslimat Adres ' + CAST(Id AS NVARCHAR(10)),
    [BillingAddress] = 'Fatura Adres ' + CAST(Id AS NVARCHAR(10)),
    [DeliveryCity] = CASE WHEN Id % 5 = 0 THEN 'İstanbul' WHEN Id % 5 = 1 THEN 'Ankara' WHEN Id % 5 = 2 THEN 'İzmir' WHEN Id % 5 = 3 THEN 'Bursa' ELSE 'Antalya' END,
    [BillingCity] = CASE WHEN Id % 5 = 0 THEN 'İstanbul' WHEN Id % 5 = 1 THEN 'Ankara' WHEN Id % 5 = 2 THEN 'İzmir' WHEN Id % 5 = 3 THEN 'Bursa' ELSE 'Antalya' END,
    [DeliveryPostalCode] = '34000',
    [BillingPostalCode] = '34000',
    [RiskLevel] = CASE WHEN Id % 3 = 0 THEN 'Düşük' WHEN Id % 3 = 1 THEN 'Orta' ELSE 'Yüksek' END,
    [CreditRating] = CASE WHEN Id % 4 = 0 THEN 'AAA' WHEN Id % 4 = 1 THEN 'AA' WHEN Id % 4 = 2 THEN 'A' ELSE 'BBB' END,
    [IsBlacklisted] = 0,
    [BlacklistReason] = NULL,
    [GdprConsent] = 1,
    [MarketingConsent] = CASE WHEN Id % 2 = 0 THEN 1 ELSE 0 END,
    [SmsConsent] = CASE WHEN Id % 2 = 0 THEN 1 ELSE 0 END,
    [EmailConsent] = CASE WHEN Id % 2 = 0 THEN 1 ELSE 0 END,
    [Language] = 'tr-TR',
    [TimeZone] = 'Turkey',
    [DateFormat] = 'dd.MM.yyyy',
    [NumberFormat] = 'tr-TR'
WHERE Email IS NULL OR Phone IS NULL OR TaxNumber IS NULL;

-- Sonuç kontrolü
SELECT COUNT(*) as UpdatedRecords FROM [BigIntSoftware].[Customers] WHERE Email IS NOT NULL AND Phone IS NOT NULL AND TaxNumber IS NOT NULL;
